/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TouchID */

#ifndef _Included_TouchID
#define _Included_TouchID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TouchID
 * Method:    authenticate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_TouchID_authenticate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
